name: 'Clean Older NuGet Package'
description:
  'Clean older NuGet package from the organization package repository'
author: 'Kevin Palencia'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  organization-package-url:
    description: 'The URL of the organization package'
    required: true
    default: ''
  gh-token:
    description: 'The GitHub token to access the organization package'
    required: true
    default: ''

# Define your outputs here.
outputs:
  versions:
    description: 'The version list of the organization package'

runs:
  using: node20
  main: dist/index.js
